version: '3.8'

services:
  mt5-api:
    build:
      context: ./api
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/config:/etc/influxdb2:ro

